/* The following code was generated by JFlex 1.4.3 on 15.19.5 12:06 */

package cz.juzna.intellij.neon.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static cz.juzna.intellij.neon.lexer.NeonTokenTypes.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15.19.5 12:06 from the specification file
 * <tt>C:/Users/Pavels.Veretennikovs/IdeaProjects/intellij-neon/src/main/java/cz/juzna/intellij/neon/lexer/neon.flex</tt>
 */
public class _NeonLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int IN_ASSIGNMENT_LITERAL = 6;
  public static final int IN_LITERAL = 2;
  public static final int YYINITIAL = 0;
  public static final int IN_ASSIGNMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\15\1\10\1\2\2\20\1\22\16\15\4\32\1\10\1\11\1\3"+
    "\1\5\1\13\1\7\1\0\1\1\1\26\1\27\2\0\1\25\1\6"+
    "\2\0\12\14\1\23\2\0\1\16\3\0\21\13\1\33\10\13\1\31"+
    "\1\4\1\24\1\0\1\13\1\11\32\13\1\12\1\0\1\30\1\0"+
    "\6\14\1\21\32\14\2\0\4\13\4\0\1\13\2\0\1\14\7\0"+
    "\1\13\4\0\1\13\5\0\27\13\1\0\37\13\1\0\u01ca\13\4\0"+
    "\14\13\16\0\5\13\7\0\1\13\1\0\1\13\21\0\160\14\5\13"+
    "\1\0\2\13\2\0\4\13\10\0\1\13\1\0\3\13\1\0\1\13"+
    "\1\0\24\13\1\0\123\13\1\0\213\13\1\0\5\14\2\0\236\13"+
    "\11\0\46\13\2\0\1\13\7\0\47\13\7\0\1\13\1\0\55\14"+
    "\1\0\1\14\1\0\2\14\1\0\2\14\1\0\1\14\10\0\33\13"+
    "\5\0\3\13\15\0\5\14\6\0\1\13\4\0\13\14\5\0\53\13"+
    "\37\14\4\0\2\13\1\14\143\13\1\0\1\13\10\14\1\0\6\14"+
    "\2\13\2\14\1\0\4\14\2\13\12\14\3\13\2\0\1\13\17\0"+
    "\1\14\1\13\1\14\36\13\33\14\2\0\131\13\13\14\1\13\16\0"+
    "\12\14\41\13\11\14\2\13\4\0\1\13\5\0\26\13\4\14\1\13"+
    "\11\14\1\13\3\14\1\13\5\14\22\0\31\13\3\14\104\0\1\13"+
    "\1\0\13\13\67\0\33\14\1\0\4\14\66\13\3\14\1\13\22\14"+
    "\1\13\7\14\12\13\2\14\2\0\12\14\1\0\7\13\1\0\7\13"+
    "\1\0\3\14\1\0\10\13\2\0\2\13\2\0\26\13\1\0\7\13"+
    "\1\0\1\13\3\0\4\13\2\0\1\14\1\13\7\14\2\0\2\14"+
    "\2\0\3\14\1\13\10\0\1\14\4\0\2\13\1\0\3\13\2\14"+
    "\2\0\12\14\4\13\7\0\1\13\5\0\3\14\1\0\6\13\4\0"+
    "\2\13\2\0\26\13\1\0\7\13\1\0\2\13\1\0\2\13\1\0"+
    "\2\13\2\0\1\14\1\0\5\14\4\0\2\14\2\0\3\14\3\0"+
    "\1\14\7\0\4\13\1\0\1\13\7\0\14\14\3\13\1\14\13\0"+
    "\3\14\1\0\11\13\1\0\3\13\1\0\26\13\1\0\7\13\1\0"+
    "\2\13\1\0\5\13\2\0\1\14\1\13\10\14\1\0\3\14\1\0"+
    "\3\14\2\0\1\13\17\0\2\13\2\14\2\0\12\14\1\0\1\13"+
    "\17\0\3\14\1\0\10\13\2\0\2\13\2\0\26\13\1\0\7\13"+
    "\1\0\2\13\1\0\5\13\2\0\1\14\1\13\7\14\2\0\2\14"+
    "\2\0\3\14\10\0\2\14\4\0\2\13\1\0\3\13\2\14\2\0"+
    "\12\14\1\0\1\13\20\0\1\14\1\13\1\0\6\13\3\0\3\13"+
    "\1\0\4\13\3\0\2\13\1\0\1\13\1\0\2\13\3\0\2\13"+
    "\3\0\3\13\3\0\14\13\4\0\5\14\3\0\3\14\1\0\4\14"+
    "\2\0\1\13\6\0\1\14\16\0\12\14\11\0\1\13\7\0\3\14"+
    "\1\0\10\13\1\0\3\13\1\0\27\13\1\0\12\13\1\0\5\13"+
    "\3\0\1\13\7\14\1\0\3\14\1\0\4\14\7\0\2\14\1\0"+
    "\2\13\6\0\2\13\2\14\2\0\12\14\22\0\2\14\1\0\10\13"+
    "\1\0\3\13\1\0\27\13\1\0\12\13\1\0\5\13\2\0\1\14"+
    "\1\13\7\14\1\0\3\14\1\0\4\14\7\0\2\14\7\0\1\13"+
    "\1\0\2\13\2\14\2\0\12\14\1\0\2\13\17\0\2\14\1\0"+
    "\10\13\1\0\3\13\1\0\51\13\2\0\1\13\7\14\1\0\3\14"+
    "\1\0\4\14\1\13\10\0\1\14\10\0\2\13\2\14\2\0\12\14"+
    "\12\0\6\13\2\0\2\14\1\0\22\13\3\0\30\13\1\0\11\13"+
    "\1\0\1\13\2\0\7\13\3\0\1\14\4\0\6\14\1\0\1\14"+
    "\1\0\10\14\22\0\2\14\15\0\60\13\1\14\2\13\7\14\4\0"+
    "\10\13\10\14\1\0\12\14\47\0\2\13\1\0\1\13\2\0\2\13"+
    "\1\0\1\13\2\0\1\13\6\0\4\13\1\0\7\13\1\0\3\13"+
    "\1\0\1\13\1\0\1\13\2\0\2\13\1\0\4\13\1\14\2\13"+
    "\6\14\1\0\2\14\1\13\2\0\5\13\1\0\1\13\1\0\6\14"+
    "\2\0\12\14\2\0\4\13\40\0\1\13\27\0\2\14\6\0\12\14"+
    "\13\0\1\14\1\0\1\14\1\0\1\14\4\0\2\14\10\13\1\0"+
    "\44\13\4\0\24\14\1\0\2\14\5\13\13\14\1\0\44\14\11\0"+
    "\1\14\71\0\53\13\24\14\1\13\12\14\6\0\6\13\4\14\4\13"+
    "\3\14\1\13\3\14\2\13\7\14\3\13\4\14\15\13\14\14\1\13"+
    "\17\14\2\0\46\13\1\0\1\13\5\0\1\13\2\0\53\13\1\0"+
    "\u014d\13\1\0\4\13\2\0\7\13\1\0\1\13\1\0\4\13\2\0"+
    "\51\13\1\0\4\13\2\0\41\13\1\0\4\13\2\0\7\13\1\0"+
    "\1\13\1\0\4\13\2\0\17\13\1\0\71\13\1\0\4\13\2\0"+
    "\103\13\2\0\3\14\40\0\20\13\20\0\125\13\14\0\u026c\13\2\0"+
    "\21\13\1\0\32\13\5\0\113\13\3\0\3\13\17\0\15\13\1\0"+
    "\4\13\3\14\13\0\22\13\3\14\13\0\22\13\2\14\14\0\15\13"+
    "\1\0\3\13\1\0\2\14\14\0\64\13\40\14\3\0\1\13\3\0"+
    "\2\13\1\14\2\0\12\14\41\0\3\14\2\0\12\14\6\0\130\13"+
    "\10\0\51\13\1\14\1\13\5\0\106\13\12\0\35\13\3\0\14\14"+
    "\4\0\14\14\12\0\12\14\36\13\2\0\5\13\13\0\54\13\4\0"+
    "\21\14\7\13\2\14\6\0\12\14\46\0\27\13\5\14\4\0\65\13"+
    "\12\14\1\0\35\14\2\0\13\14\6\0\12\14\15\0\1\13\130\0"+
    "\5\14\57\13\21\14\7\13\4\0\12\14\21\0\11\14\14\0\3\14"+
    "\36\13\15\14\2\13\12\14\54\13\16\14\14\0\44\13\24\14\10\0"+
    "\12\14\3\0\3\13\12\14\44\13\122\0\3\14\1\0\25\14\4\13"+
    "\1\14\4\13\3\14\2\13\11\0\300\13\47\14\25\0\4\14\u0116\13"+
    "\2\0\6\13\2\0\46\13\2\0\6\13\2\0\10\13\1\0\1\13"+
    "\1\0\1\13\1\0\1\13\1\0\37\13\2\0\65\13\1\0\7\13"+
    "\1\0\1\13\3\0\3\13\1\0\7\13\3\0\4\13\2\0\6\13"+
    "\4\0\15\13\5\0\3\13\1\0\7\13\16\0\5\14\30\0\2\17"+
    "\5\14\20\0\2\13\23\0\1\13\13\0\5\14\5\0\6\14\1\0"+
    "\1\13\15\0\1\13\20\0\15\13\3\0\33\13\25\0\15\14\4\0"+
    "\1\14\3\0\14\14\21\0\1\13\4\0\1\13\2\0\12\13\1\0"+
    "\1\13\3\0\5\13\6\0\1\13\1\0\1\13\1\0\1\13\1\0"+
    "\4\13\1\0\13\13\2\0\4\13\5\0\5\13\4\0\1\13\21\0"+
    "\51\13\u0a77\0\57\13\1\0\57\13\1\0\205\13\6\0\4\13\3\14"+
    "\2\13\14\0\46\13\1\0\1\13\5\0\1\13\2\0\70\13\7\0"+
    "\1\13\17\0\1\14\27\13\11\0\7\13\1\0\7\13\1\0\7\13"+
    "\1\0\7\13\1\0\7\13\1\0\7\13\1\0\7\13\1\0\7\13"+
    "\1\0\40\14\57\0\1\13\u01d5\0\3\13\31\0\11\13\6\14\1\0"+
    "\5\13\2\0\5\13\4\0\126\13\2\0\2\14\2\0\3\13\1\0"+
    "\132\13\1\0\4\13\5\0\51\13\3\0\136\13\21\0\33\13\65\0"+
    "\20\13\u0200\0\u19b6\13\112\0\u51cd\13\63\0\u048d\13\103\0\56\13\2\0"+
    "\u010d\13\3\0\20\13\12\14\2\13\24\0\57\13\1\14\4\0\12\14"+
    "\1\0\31\13\7\0\1\14\120\13\2\14\45\0\11\13\2\0\147\13"+
    "\2\0\4\13\1\0\4\13\14\0\13\13\115\0\12\13\1\14\3\13"+
    "\1\14\4\13\1\14\27\13\5\14\20\0\1\13\7\0\64\13\14\0"+
    "\2\14\62\13\21\14\13\0\12\14\6\0\22\14\6\13\3\0\1\13"+
    "\4\0\12\14\34\13\10\14\2\0\27\13\15\14\14\0\35\13\3\0"+
    "\4\14\57\13\16\14\16\0\1\13\12\14\46\0\51\13\16\14\11\0"+
    "\3\13\1\14\10\13\2\14\2\0\12\14\6\0\27\13\3\0\1\13"+
    "\1\14\4\0\60\13\1\14\1\13\3\14\2\13\2\14\5\13\2\14"+
    "\1\13\1\14\1\13\30\0\3\13\2\0\13\13\5\14\2\0\3\13"+
    "\2\14\12\0\6\13\2\0\6\13\2\0\6\13\11\0\7\13\1\0"+
    "\7\13\221\0\43\13\10\14\1\0\2\14\2\0\12\14\6\0\u2ba4\13"+
    "\14\0\27\13\4\0\61\13\u2104\0\u016e\13\2\0\152\13\46\0\7\13"+
    "\14\0\5\13\5\0\1\13\1\14\12\13\1\0\15\13\1\0\5\13"+
    "\1\0\1\13\1\0\2\13\1\0\2\13\1\0\154\13\41\0\u016b\13"+
    "\22\0\100\13\2\0\66\13\50\0\15\13\3\0\20\14\20\0\7\14"+
    "\14\0\2\13\30\0\3\13\31\0\1\13\6\0\5\13\1\0\207\13"+
    "\2\0\1\14\4\0\1\13\13\0\12\14\7\0\32\13\4\0\1\13"+
    "\1\0\32\13\13\0\131\13\3\0\6\13\2\0\6\13\2\0\6\13"+
    "\2\0\3\13\3\0\2\13\3\0\2\13\22\0\3\14\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\3\1\5\1\2"+
    "\1\6\1\3\1\7\2\2\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\2\20\1\17\1\21\3\22"+
    "\1\23\1\22\1\24\2\25\1\1\1\26\1\27\1\0"+
    "\1\30\2\0\1\31\1\0\1\31\1\0\1\32\2\33"+
    "\1\17\1\0\2\34\1\0\1\35\4\0\1\36\1\0"+
    "\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\34\0\70\0\124\0\160\0\214\0\250\0\304"+
    "\0\340\0\374\0\u0118\0\u0134\0\214\0\u0150\0\u016c\0\u0188"+
    "\0\214\0\214\0\214\0\214\0\214\0\214\0\u01a4\0\u01c0"+
    "\0\214\0\u01dc\0\u01f8\0\214\0\u0214\0\214\0\u0230\0\u024c"+
    "\0\u0268\0\214\0\214\0\u0284\0\u02a0\0\214\0\u02a0\0\250"+
    "\0\214\0\340\0\u02bc\0\214\0\u02d8\0\u02f4\0\u016c\0\214"+
    "\0\214\0\u0310\0\214\0\u01dc\0\214\0\u032c\0\u0214\0\214"+
    "\0\u0230\0\u0348\0\u0284\0\u0364\0\u0380\0\u039c\0\214";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\6\1\12\1\13\1\6"+
    "\1\14\1\15\1\16\1\17\1\6\2\15\1\6\1\15"+
    "\1\6\1\15\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\15\1\17\1\6\1\7\1\10\1\11\1\6"+
    "\1\12\1\13\1\27\1\14\1\15\1\16\1\17\1\6"+
    "\2\15\1\6\1\15\1\6\1\15\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\15\1\17\2\30\1\31"+
    "\5\30\1\32\4\30\1\31\2\30\1\31\1\30\1\31"+
    "\1\33\5\31\1\30\1\31\1\30\1\34\1\35\1\36"+
    "\1\37\1\34\1\36\2\34\1\40\1\36\1\41\2\34"+
    "\1\36\1\42\1\34\1\36\1\34\1\36\1\34\7\36"+
    "\1\34\2\43\1\0\5\43\1\44\2\43\3\45\1\46"+
    "\2\43\1\45\11\43\1\47\34\0\1\50\1\51\1\0"+
    "\31\50\10\0\1\10\23\0\2\52\1\0\1\51\1\53"+
    "\27\52\2\12\1\0\31\12\2\0\1\54\3\0\1\55"+
    "\1\0\1\54\6\0\3\54\1\56\21\0\1\14\35\0"+
    "\1\6\34\0\3\57\1\60\2\0\1\57\11\0\1\57"+
    "\2\0\1\61\5\0\1\61\6\0\3\61\1\62\1\0"+
    "\2\61\1\0\2\61\3\0\2\27\1\0\31\27\2\30"+
    "\1\0\5\30\1\0\4\30\1\0\2\30\1\0\1\30"+
    "\7\0\1\30\1\0\1\30\2\63\1\0\2\63\1\0"+
    "\2\63\1\64\4\63\1\0\2\63\1\0\1\63\7\0"+
    "\1\63\1\0\1\63\2\0\1\31\5\0\1\31\6\0"+
    "\3\65\1\66\1\0\2\31\1\0\2\31\3\0\1\67"+
    "\1\70\1\0\31\67\2\71\1\0\1\70\1\72\27\71"+
    "\10\0\1\40\35\0\1\34\31\0\1\73\2\0\1\74"+
    "\17\0\1\74\13\0\3\45\3\0\1\45\11\0\1\45"+
    "\2\52\1\0\31\52\6\0\1\75\27\0\1\54\33\0"+
    "\1\61\33\0\1\65\31\0\2\71\1\0\31\71\10\0"+
    "\1\76\2\0\3\74\1\77\2\0\1\74\11\0\1\74"+
    "\2\75\1\0\31\75\10\0\1\76\5\0\1\77\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[952];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\1\1\11\6\1\1\11\3\1\6\11\2\1"+
    "\1\11\2\1\1\11\1\1\1\11\3\1\2\11\2\1"+
    "\1\11\1\1\1\0\1\11\2\0\1\11\1\0\1\1"+
    "\1\0\2\11\1\1\1\11\1\0\1\11\1\1\1\0"+
    "\1\11\4\0\1\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    private int yycolumn = 0;
    private int a = 0;
	private void retryInState(int newState) {
        yybegin(newState);
        yypushback(yylength());
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _NeonLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL-1] : zzBufferL.charAt(zzMarkedPosL-1))) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [88] { return NEON_UNKNOWN; }");
          { return NEON_UNKNOWN;
          }
        case 32: break;
        case 25: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [56] { return NEON_ARRAY_BULLET; }");
          { return NEON_ARRAY_BULLET;
          }
        case 33: break;
        case 26: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [40] { a=2;retryInState(IN_ASSIGNMENT); }");
          { a=2;retryInState(IN_ASSIGNMENT);
          }
        case 34: break;
        case 7: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [64] { return NEON_LBRACE_CURLY; }");
          { return NEON_LBRACE_CURLY;
          }
        case 35: break;
        case 20: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [113] { a=402;return NEON_ASSIGNMENT; }");
          { a=402;return NEON_ASSIGNMENT;
          }
        case 36: break;
        case 13: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [68] { return NEON_LBRACE_SQUARE; }");
          { return NEON_LBRACE_SQUARE;
          }
        case 37: break;
        case 5: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [71] { return NEON_COMMENT; }");
          { return NEON_COMMENT;
          }
        case 38: break;
        case 2: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [79] { yybegin(IN_LITERAL);"+ZZ_NL+"        return NEON_LITERAL; }");
          { yybegin(IN_LITERAL);
        return NEON_LITERAL;
          }
        case 39: break;
        case 19: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [114] { a=403;return NEON_WHITESPACE; }");
          { a=403;return NEON_WHITESPACE;
          }
        case 40: break;
        case 18: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [122] { a=406;retryInState(YYINITIAL); }");
          { a=406;retryInState(YYINITIAL);
          }
        case 41: break;
        case 14: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [48] { return NEON_TAG; }");
          { return NEON_TAG;
          }
        case 42: break;
        case 22: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [104] { a=502; retryInState(IN_ASSIGNMENT); }");
          { a=502; retryInState(IN_ASSIGNMENT);
          }
        case 43: break;
        case 1: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [107] { a=504; }");
          { a=504;
          }
        case 44: break;
        case 10: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [62] { return NEON_LPAREN; }");
          { return NEON_LPAREN;
          }
        case 45: break;
        case 9: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [60] { return NEON_ITEM_DELIMITER; }");
          { return NEON_ITEM_DELIMITER;
          }
        case 46: break;
        case 11: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [63] { return NEON_RPAREN; }");
          { return NEON_RPAREN;
          }
        case 47: break;
        case 27: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [58] { return NEON_COLON; }");
          { return NEON_COLON;
          }
        case 48: break;
        case 8: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [69] { return NEON_RBRACE_SQUARE; }");
          { return NEON_RBRACE_SQUARE;
          }
        case 49: break;
        case 24: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [44] { return NEON_STRING; }");
          { return NEON_STRING;
          }
        case 50: break;
        case 21: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [108] { a=505; }");
          { a=505;
          }
        case 51: break;
        case 12: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [65] { return NEON_RBRACE_CURLY; }");
          { return NEON_RBRACE_CURLY;
          }
        case 52: break;
        case 28: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [97] { retryInState(YYINITIAL); }");
          { retryInState(YYINITIAL);
          }
        case 53: break;
        case 16: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [99] { retryInState(YYINITIAL); }");
          { retryInState(YYINITIAL);
          }
        case 54: break;
        case 4: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [75] { return NEON_INDENT; }");
          { return NEON_INDENT;
          }
        case 55: break;
        case 31: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [103] { a=501; retryInState(IN_ASSIGNMENT); }");
          { a=501; retryInState(IN_ASSIGNMENT);
          }
        case 56: break;
        case 17: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [117] { a=405;retryInState(IN_ASSIGNMENT_LITERAL);"+ZZ_NL+"        return NEON_LITERAL; }");
          { a=405;retryInState(IN_ASSIGNMENT_LITERAL);
        return NEON_LITERAL;
          }
        case 57: break;
        case 23: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [105] { a=503;retryInState(IN_ASSIGNMENT); }");
          { a=503;retryInState(IN_ASSIGNMENT);
          }
        case 58: break;
        case 29: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [112] { a=401;return NEON_STRING; }");
          { a=401;return NEON_STRING;
          }
        case 59: break;
        case 6: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [84] { return NEON_WHITESPACE; }");
          { return NEON_WHITESPACE;
          }
        case 60: break;
        case 30: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [52] { return NEON_HEADER; }");
          { return NEON_HEADER;
          }
        case 61: break;
        case 15: 
          System.out.println("match: --"+yytext()+"--");
          System.out.println("action [94] {  }");
          { 
          }
        case 62: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java _NeonLexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        _NeonLexer scanner = null;
        try {
          scanner = new _NeonLexer( new java.io.FileReader(argv[i]) );
          do {
            System.out.println(scanner.advance());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
